### ISSUE TITLE
Does it work on a Raspberry Pico?

### ISSUE THREAD

**Issue by davidedelvento** [sparkfun/SparkFun_Qwiic_OLED_1.3in#1]
Would this display (or another one) work with a Pico? Obviously not with the Arduino library but with something else?

How about the original Teensy v4.1 from PJRC? Would that work out of the box?

Thanks

**Comment by PaulZC** [comment]
Hi Davide (@davidedelvento ),

Earle Philhower's RP2040 Arduino board package supports I2C. If you use that, you should find that our [Qwiic OLED Library](https://github.com/sparkfun/SparkFun_Qwiic_OLED_Arduino_Library) works just fine.

![image](https://github.com/user-attachments/assets/1dfcbf3b-635a-4011-83be-1d251e1183fa)

Best wishes,
Paul

**Comment by davidedelvento** [comment]
Sounds great! Thanks a lot Paul, especially for responding during the weekend.
Just for reference for others coming here (and not willing to Google :rofl: ), Earle's Arduino port is a at https://github.com/earlephilhower/arduino-pico
